### ISSUE TITLE
Week 1 - Migrate all of the tasks onto new board

### ISSUE THREAD

**Issue by servercetinbe** [servercetinbe/mertcan-fe#1]

**Comment by servercetinbe** [comment]
We should migrate our the tasks we have done on the other board
https://github.com/enginmertcan/Javascript/

1. We should seperate the progress by weeks, and categories 
For example 
01 Week: Basics
- Day 1
- Day 2

2. Every categoric fold should have readme.md
For example every week should have readme.md and it should describe what is gonna be in this week, what are you planning to do etc.
Day 1 represents monday, Day 2 tuesday ... We should name these files according the days, and we should report the day progresses on week readmes.

**Comment by enginmertcan** [comment]
All tasks have been successfully migrated to the new board. Prior to migration, existing files were translated into English, and README documents were added to provide context
