### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by servercetinbe** [servercetinbe/mertcan-fe#2]
1. HTML Section on roadmap.sh (accessibility, SEO Basics, Forms and validations, semantic HTML, Basics)
2. What is package managers, and why we use them? What is npm and pnpm, install pnpm and descripe 4 of its command 
- For example: npm install, pnpm i what does it do
3. CSS Architecture, what is BEM, why we use it?
4. Sass, SCSS what are they? Why we use them?
5. What is the difference between FE frameworks, why can I choose React or Vue, compare them.

**Comment by enginmertcan** [comment]
I have completed the assigned task. I thoroughly researched and studied the following topics:
HTML Section (Accessibility, SEO Basics, Forms and Validations, Semantic HTML, Basics).
Package Managers: What are npm and pnpm, installation, and their commands .
CSS Architecture: What is BEM and why we use it.
Sass and SCSS: What they are and why we use them.
Comparison of Frontend frameworks (React vs Vue).
